name: "Terraform Deployment"

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: ./infra/terraform
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Criar arquivo terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          aws_region = "${{ secrets.AWS_REGION }}"
          instance_type = "${{ secrets.INSTANCE_TYPE }}"
          spot_price = "${{ secrets.SPOT_PRICE }}"
          ami_id = "${{ secrets.AMI_ID }}"
          vpc_id = "${{ secrets.VPC_ID }}"
          subnet_id = "${{ secrets.SUBNET_ID }}"
          nat_instance_id = "${{ secrets.NAT_INSTANCE_ID }}"
          instance_security_group_id = "${{ secrets.INSTANCE_SECURITY_GROUP_ID }}"
          EOF

      - name: Verificar conteúdo do terraform.tfvars
        run: |
          echo "=== Início do arquivo ==="
          cat -A terraform.tfvars  # Mostra caracteres especiais
          echo "=== Fim do arquivo ==="

      - name: Verificar conteúdo do arquivo
        run: cat terraform.tfvars

      - name: Terraform Init
        run: terraform init -backend-config=production.tfbackend

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -var-file=terraform.tfvars -auto-approve
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
